language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
sudo: true
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s tests/
  - coverage run --source=xray/ -m unittest discover -s tests/ && coverage report -m
  - python -m pylint -E main.py --disable=R,C,W
  - python -m pylint xray/*.py --disable=R,C,W,too-many-function-args,import-error
